"""
India Electricity Forecasting — Interactive Dashboard
--------------------------------------------------------
Combines every output from the pipeline into one browsable app.

Run with:
    streamlit run dashboard.py

Expects these files in the same folder (all already generated by earlier
scripts in this project):
    india_electricity_master.xlsx
    avg_daily_demand_forecast_2040.xlsx
    avg_daily_generation_forecast_2040.xlsx
    demand_supply_gap.xlsx
"""

from pathlib import Path

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

st.set_page_config(page_title="India Electricity Forecast", layout="wide")

BASE_DIR = Path(__file__).resolve().parent
MASTER_FILE = BASE_DIR / "india_electricity_master.xlsx"
DEMAND_FORECAST_FILE = BASE_DIR / "avg_daily_demand_forecast_2040.xlsx"
GENERATION_FORECAST_FILE = BASE_DIR / "avg_daily_generation_forecast_2040.xlsx"
GAP_FILE = BASE_DIR / "demand_supply_gap.xlsx"

ERA_CUTOFF = pd.Timestamp("2017-05-26")
CHECKPOINT_YEARS = [2026, 2030, 2035, 2040]


# ----------------------------------------------------------------------
# DATA LOADING (cached so the app doesn't re-read files on every click)
# ----------------------------------------------------------------------

@st.cache_data
def load_master():
    master = pd.read_excel(MASTER_FILE, sheet_name="MASTER_monthly")
    master["year_month"] = pd.PeriodIndex(master["year_month"], freq="M")
    master["date"] = master["year_month"].dt.to_timestamp()
    harmonized = pd.read_excel(MASTER_FILE, sheet_name="gen_by_source_harmonized")
    harmonized["date"] = pd.to_datetime(harmonized["date"])
    return master, harmonized


@st.cache_data
def load_forecasts():
    demand = pd.read_excel(DEMAND_FORECAST_FILE, index_col=0)
    demand.index = pd.to_datetime(demand.index)
    generation = pd.read_excel(GENERATION_FORECAST_FILE, index_col=0)
    generation.index = pd.to_datetime(generation.index)
    return demand, generation


@st.cache_data
def load_gap():
    gap = pd.read_excel(GAP_FILE, index_col=0)
    gap.index = pd.to_datetime(gap.index)
    return gap


data_loaded = False
missing_file = ""

try:
    master, harmonized = load_master()
    demand_fc, generation_fc = load_forecasts()
    gap_df = load_gap()
    data_loaded = True
except Exception as e:
    data_loaded = False
    missing_file = str(e)

st.title("India Electricity Demand, Generation & Energy Mix Forecast")

if not data_loaded:
    st.error(
        "Could not load the required dashboard data.\n\n"
        f"Detail: {missing_file}\n\n"
        "Make sure the pipeline output files exist in the same folder as this "
        "dashboard script and that you have run the full pipeline before opening "
        "the dashboard."
    )
    st.stop()


tab1, tab2, tab3, tab4 = st.tabs([
    "Historical Trends", "Source Mix", "Forecast to 2040", "Demand-Supply Gap"
])


# ----------------------------------------------------------------------
# TAB 1 — Historical Trends
# ----------------------------------------------------------------------

with tab1:
    st.subheader("Generation, Demand & Consumption — Historical (2013-2024)")

    metric = st.selectbox(
        "Metric", ["avg_daily_generation", "avg_daily_demand", "avg_daily_consumption"]
    )

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=master["date"], y=master[metric], mode="lines", name=metric
    ))

    low_cov = master[master["low_coverage_flag"]]
    if len(low_cov):
        fig.add_trace(go.Scatter(
            x=low_cov["date"], y=low_cov[metric], mode="markers",
            name="Low-coverage month (interpolated)",
            marker=dict(color="orange", size=8, symbol="x")
        ))

    fig.add_vline(x=ERA_CUTOFF, line_dash="dash", line_color="red",
                   annotation_text="CEA reporting-format change")

    fig.update_layout(height=500, xaxis_title="Date", yaxis_title=metric)
    st.plotly_chart(fig, use_container_width=True)

    st.caption(
        "Orange X markers show months that were interpolated due to severe "
        "under-reporting in the raw data (fewer than 20 days reported that "
        "month) — see the project's data integrity notes for details."
    )


# ----------------------------------------------------------------------
# TAB 2 — Source Mix
# ----------------------------------------------------------------------

with tab2:
    st.subheader("Generation Source Mix — % Share (Dec 2018 onward)")
    st.caption(
        "Scoped to Dec 2018+ because Coal/Lignite itemization is unreliable "
        "before that date in the raw CEA data (see data integrity notes)."
    )

    reliable_start = pd.Timestamp("2018-12-01")
    detailed = harmonized[harmonized["date"] >= reliable_start].copy()
    detailed["year_month"] = detailed["date"].dt.to_period("M")
    monthly = detailed.groupby("year_month")[
        ["coal_lignite_mu", "renewables_mu", "hydro_mu", "nuclear_mu", "gas_naptha_diesel_mu"]
    ].mean()
    monthly.index = monthly.index.to_timestamp()
    share = monthly.div(monthly.sum(axis=1), axis=0) * 100

    fig = go.Figure()
    for col in share.columns:
        fig.add_trace(go.Scatter(
            x=share.index, y=share[col], mode="lines", stackgroup="one", name=col
        ))
    fig.update_layout(height=550, yaxis_title="% share", xaxis_title="Date")
    st.plotly_chart(fig, use_container_width=True)

    col1, col2 = st.columns(2)
    col1.metric("Renewables share (first month)", f"{share['renewables_mu'].iloc[0]:.1f}%")
    col2.metric("Renewables share (latest month)", f"{share['renewables_mu'].iloc[-1]:.1f}%")


# ----------------------------------------------------------------------
# TAB 3 — Forecast to 2040
# ----------------------------------------------------------------------

with tab3:
    st.subheader("Demand & Generation Forecast to 2040")
    st.caption(
        "Only the first 24 months of forecast are empirically validated "
        "via walk-forward testing. Everything beyond that (shaded lighter) "
        "is a trend-based scenario extrapolation, not a precise prediction."
    )

    fig = go.Figure()
    for name, df, color in [("Demand", demand_fc, "red"), ("Generation", generation_fc, "blue")]:
        validated = df[df["is_validated_horizon"]]
        extrapolated = df[~df["is_validated_horizon"]]

        fig.add_trace(go.Scatter(
            x=validated.index, y=validated["forecast"], mode="lines",
            name=f"{name} (validated)", line=dict(color=color)
        ))
        fig.add_trace(go.Scatter(
            x=extrapolated.index, y=extrapolated["forecast"], mode="lines",
            name=f"{name} (extrapolated)", line=dict(color=color, dash="dash")
        ))
        fig.add_trace(go.Scatter(
            x=list(df.index) + list(df.index[::-1]),
            y=list(df["ci_upper_95"]) + list(df["ci_lower_95"][::-1]),
            fill="toself", fillcolor=color, opacity=0.1,
            line=dict(width=0), showlegend=False, hoverinfo="skip"
        ))

    fig.update_layout(height=600, xaxis_title="Date", yaxis_title="Avg Daily (MU)")
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Checkpoint Forecasts")
    rows = []
    for year in CHECKPOINT_YEARS:
        target = pd.Timestamp(f"{year}-12-01")
        if target in demand_fc.index and target in generation_fc.index:
            rows.append({
                "Year": year,
                "Demand (MU/day)": f"{demand_fc.loc[target, 'forecast']:,.0f}",
                "Demand 95% CI": f"[{demand_fc.loc[target, 'ci_lower_95']:,.0f}, {demand_fc.loc[target, 'ci_upper_95']:,.0f}]",
                "Generation (MU/day)": f"{generation_fc.loc[target, 'forecast']:,.0f}",
                "Generation 95% CI": f"[{generation_fc.loc[target, 'ci_lower_95']:,.0f}, {generation_fc.loc[target, 'ci_upper_95']:,.0f}]",
            })
    st.table(pd.DataFrame(rows).set_index("Year"))


# ----------------------------------------------------------------------
# TAB 4 — Demand-Supply Gap (with scenario slider)
# ----------------------------------------------------------------------

with tab4:
    st.subheader("Demand-Supply Gap, with Adjustable Generation Growth Scenario")

    st.warning(
        "Note: the shaded 'worst/best case' range treats demand and generation "
        "uncertainty as independent, which likely overstates the true worst "
        "case — historically the two move together. Treat the point estimate "
        "(black line) as the primary read, not the shaded extremes."
    )

    growth_adjustment = st.slider(
        "Adjust generation growth assumption (illustrative scenario, %/year)",
        min_value=-5.0, max_value=5.0, value=0.0, step=0.5,
        help="Applies a simple compounding adjustment to the generation "
             "forecast to illustrate 'what if generation grew faster/slower "
             "than the trend model assumes' — e.g. from accelerated renewable "
             "capacity additions. This is an illustrative adjustment, not a "
             "re-fit model."
    )

    gen_adjusted = generation_fc["forecast"].copy()
    if growth_adjustment != 0:
        months_out = (gen_adjusted.index.year - gen_adjusted.index[0].year) * 12 + \
                     (gen_adjusted.index.month - gen_adjusted.index[0].month)
        multiplier = (1 + growth_adjustment / 100) ** (months_out / 12)
        gen_adjusted = gen_adjusted * multiplier

    gap_adjusted = gen_adjusted - demand_fc["forecast"]

    fig = make_subplots(rows=2, cols=1, shared_xaxes=True,
                         row_heights=[0.6, 0.4],
                         subplot_titles=("Demand vs Generation (adjusted)", "Gap"))

    fig.add_trace(go.Scatter(x=demand_fc.index, y=demand_fc["forecast"],
                              name="Demand", line=dict(color="red")), row=1, col=1)
    fig.add_trace(go.Scatter(x=gen_adjusted.index, y=gen_adjusted,
                              name="Generation (adjusted)", line=dict(color="blue")), row=1, col=1)

    fig.add_trace(go.Scatter(x=gap_adjusted.index, y=gap_adjusted,
                              name="Gap", line=dict(color="black")), row=2, col=1)
    fig.add_hline(y=0, line_dash="dash", line_color="red", row=2, col=1)

    fig.update_layout(height=700)
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Checkpoint Gap (with current scenario adjustment)")
    rows = []
    for year in CHECKPOINT_YEARS:
        target = pd.Timestamp(f"{year}-12-01")
        if target in gap_adjusted.index:
            status = "Surplus" if gap_adjusted.loc[target] >= 0 else "Shortfall"
            rows.append({
                "Year": year,
                "Gap (MU/day)": f"{gap_adjusted.loc[target]:+,.0f}",
                "Status": status,
            })
    st.table(pd.DataFrame(rows).set_index("Year"))
