"""
Demand-Supply Gap Analysis
------------------------------
Combines the demand and generation forecasts (each already generated by
final_forecast.py) into the single most important output of this
project: is India's generation growth keeping pace with demand growth,
and if not, how large is the gap and when does it emerge?

Requires both:
  avg_daily_demand_forecast_2040.xlsx
  avg_daily_generation_forecast_2040.xlsx
(run final_forecast.py once per target first if these don't exist yet)
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

FIG_DIR = Path("figures")
FIG_DIR.mkdir(exist_ok=True)

DEMAND_FILE = "avg_daily_demand_forecast_2040.xlsx"
GENERATION_FILE = "avg_daily_generation_forecast_2040.xlsx"
CHECKPOINT_YEARS = [2026, 2030, 2035, 2040]


def load_forecast(path):
    df = pd.read_excel(path, index_col=0)
    df.index = pd.to_datetime(df.index)
    return df


def main():
    demand = load_forecast(DEMAND_FILE)
    generation = load_forecast(GENERATION_FILE)

    combined = pd.DataFrame({
        "demand_forecast": demand["forecast"],
        "demand_ci_lower": demand["ci_lower_95"],
        "demand_ci_upper": demand["ci_upper_95"],
        "generation_forecast": generation["forecast"],
        "generation_ci_lower": generation["ci_lower_95"],
        "generation_ci_upper": generation["ci_upper_95"],
    })

    # Gap = generation minus demand. Positive = surplus, negative = shortfall.
    combined["gap"] = combined["generation_forecast"] - combined["demand_forecast"]
    # Worst-case gap: generation at its lower CI bound vs demand at its upper bound
    combined["gap_worst_case"] = combined["generation_ci_lower"] - combined["demand_ci_upper"]
    combined["gap_best_case"] = combined["generation_ci_upper"] - combined["demand_ci_lower"]

    print("=" * 70)
    print("DEMAND-SUPPLY GAP AT CHECKPOINT YEARS")
    print("=" * 70)
    for year in CHECKPOINT_YEARS:
        target_date = pd.Timestamp(f"{year}-12-01")
        if target_date not in combined.index:
            continue
        row = combined.loc[target_date]
        status = "SURPLUS" if row["gap"] >= 0 else "SHORTFALL"
        print(f"\n{year}:")
        print(f"  Demand forecast:     {row['demand_forecast']:,.0f} MU/day")
        print(f"  Generation forecast: {row['generation_forecast']:,.0f} MU/day")
        print(f"  Gap (point estimate): {row['gap']:+,.0f} MU/day ({status})")
        print(f"  Worst case (low generation vs high demand): {row['gap_worst_case']:+,.0f} MU/day")
        print(f"  Best case (high generation vs low demand):  {row['gap_best_case']:+,.0f} MU/day")

    # Find the first month, if any, where the worst-case scenario shows a
    # genuine shortfall — the single most useful "so what" number for the report
    shortfall_months = combined[combined["gap_worst_case"] < 0]
    if len(shortfall_months) > 0:
        first_shortfall = shortfall_months.index[0]
        print(f"\n  Under the worst-case scenario (low generation growth, high "
              f"demand growth), a shortfall first appears around "
              f"{first_shortfall.strftime('%Y-%m')}.")
    else:
        print("\n  Even under the worst-case scenario tested, generation stays "
              "ahead of demand through 2040 — though remember both forecasts "
              "are trend extrapolations beyond ~2027, not certainties.")

    # Plot
    fig, axes = plt.subplots(2, 1, figsize=(14, 10), sharex=True,
                              gridspec_kw={"height_ratios": [2, 1]})

    ax1 = axes[0]
    ax1.plot(combined.index, combined["demand_forecast"], label="Demand forecast", color="tab:red")
    ax1.fill_between(combined.index, combined["demand_ci_lower"], combined["demand_ci_upper"],
                      color="tab:red", alpha=0.15)
    ax1.plot(combined.index, combined["generation_forecast"], label="Generation forecast", color="tab:blue")
    ax1.fill_between(combined.index, combined["generation_ci_lower"], combined["generation_ci_upper"],
                      color="tab:blue", alpha=0.15)
    for year in CHECKPOINT_YEARS:
        ax1.axvline(pd.Timestamp(f"{year}-12-01"), color="gray", linestyle=":", alpha=0.4)
    ax1.set_title("India: Demand vs Generation Forecast to 2040\n(shaded = 95% confidence interval)")
    ax1.set_ylabel("Avg Daily (MU)")
    ax1.legend(loc="upper left")

    ax2 = axes[1]
    ax2.plot(combined.index, combined["gap"], color="black", label="Gap (point estimate)")
    ax2.fill_between(combined.index, combined["gap_worst_case"], combined["gap_best_case"],
                      color="gray", alpha=0.25, label="Gap range (worst to best case)")
    ax2.axhline(0, color="red", linestyle="--", alpha=0.7, label="Break-even (supply = demand)")
    for year in CHECKPOINT_YEARS:
        ax2.axvline(pd.Timestamp(f"{year}-12-01"), color="gray", linestyle=":", alpha=0.4)
    ax2.set_title("Demand-Supply Gap (Generation minus Demand)")
    ax2.set_ylabel("Gap (MU/day)")
    ax2.set_xlabel("Year")
    ax2.legend(loc="upper left")

    plt.tight_layout()
    fname = FIG_DIR / "demand_supply_gap.png"
    plt.savefig(fname, dpi=120)
    plt.close()
    print(f"\nSaved: {fname}")

    combined.to_excel("demand_supply_gap.xlsx")
    print("Saved: demand_supply_gap.xlsx")


if __name__ == "__main__":
    main()
